### ISSUE TITLE
Google Dialer Not Compatible Message

### ISSUE THREAD

**Issue by psyscope** [Magisk-Modules-Repo/GoogleDialerFramework#10]
With the most recent Google Phone update, the dialer works, but I get a message now that my phone is not compatible and may have issues. Amy chance you will update the framework for this?

**Comment by TheJulianJES** [comment]
This *should* have been fixed a year ago, I’ll see why the message reappears again soon.

**Comment by TheJulianJES** [comment]
Does this bug still occur with (the latest versions) of the Google Dialer app?
If it does, could you please post information about which phone and ROM you're using? Thanks!

**Comment by robertototaro** [comment]
Hello, I have this issue with the latest Google Dialer beta (55.1.335513515). I am using a OnePlus 6 with OOS 10.3.6 and the latest Magisk version.

I tried removing Google Dialer and the Google Dialer Framework module, reinstall everything, but I still have the same problem.

Strangely, it appeared after I cleared the Google Dialer data. Until then I have never seen that message, and now I can't get rid of it.

**Comment by psyscope** [comment]
Try removing google dialer framework will it work? For some reason on
Op7Pro recent build I didn't need google dialer. Maybe they added it to os
since it is available on Nord.

**Comment by robertototaro** [comment]
Thanks for the suggestion. Although I did it yesterday and it didn't solve the problem, I tried again and this time it worked. Maybe yesterday I didn't clean up everything before reinstalling the Dialer. Whatever the reason, you were right. 👏

**Comment by chuppito** [comment]
hello, same problem in France on pixel 6 Android 13. I tried to remove the module then put it back, still the same message
